### ISSUE TITLE
Remove lodash dependency for merge

### ISSUE THREAD

**Issue by pke** [lev-kuznetsov/node-fetch-middleware#11]
I think all merge calls can be replaced with ES destructuring and splashing composition.

https://github.com/lev-kuznetsov/node-fetch-middleware/blob/51a3edbc13222d2f98c6db234daddc1f4477399c/src/bearer.ts#L10

I wanted to create a PR but all the current tests don't run:

```bash
01:50 $ npm t

> node-fetch-middleware@0.0.0-development test /var/storage/dev/projects/oss/node-fetch-middleware
> mocha


/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/ts-node/src/index.ts:293
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/cache.ts:6:7 - error TS2395: Individual declarations in merged declaration 'cache' must be all exported or all local.

6 const cache = new NodeCache()
        ~~~~~
src/cache.ts:21:17 - error TS2395: Individual declarations in merged declaration 'cache' must be all exported or all local.

21 export function cache(options: CacheOptions = {}): Middleware {
                   ~~~~~
src/cache.ts:25:29 - error TS2339: Property 'get' does not exist on type '(options?: CacheOptions) => Middleware'.

25     get: async key => cache.get(key) as Response,
                               ~~~
src/cache.ts:26:47 - error TS2339: Property 'set' does not exist on type '(options?: CacheOptions) => Middleware'.

26     set: async (key, response, ttl) => {cache.set(key, response, ttl)}
                                                 ~~~

    at createTSError (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/ts-node/src/index.ts:293:12)
    at reportTSError (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/ts-node/src/index.ts:297:19)
    at getOutput (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/ts-node/src/index.ts:399:34)
    at Object.compile (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/ts-node/src/index.ts:457:32)
    at Module.m._compile (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/ts-node/src/index.ts:536:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Object.require.extensions.<computed> [as .ts] (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/storage/dev/projects/oss/node-fetch-middleware/src/index.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Module.m._compile (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Object.require.extensions.<computed> [as .ts] (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/storage/dev/projects/oss/node-fetch-middleware/test/bearer-test.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Module.m._compile (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Object.require.extensions.<computed> [as .ts] (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /var/storage/dev/projects/oss/node-fetch-middleware/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/var/storage/dev/projects/oss/node-fetch-middleware/node_modules/mocha/bin/mocha:164:29)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11
npm ERR! Test failed.  See above for more details.
✘-1 ~/dev-oss/node-fetch-middleware [master|✔]
```

Maybe we could also switch tests to jest and get --coverage for free?

**Comment by lev-kuznetsov** [comment]
This is due to "fixing" of the "typo" before; I reverted that. I knew there was a reason why I named it `cash` after all.
